---
- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
        key_name: mykey
        aws_access_key: "AKIAZMXYGV2LOBE7V7OW"
        aws_secret_key: ""
        group: launch-wizard-3
        instance_type: t2.micro
        image: ami-02354e95b39ca8dec
        wait: true
        region: us-east-1

      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
    - name: Get the Ip address
      debug: var=ec2.instances[0].public_dns_name
    
    - name: add host to group 'just_created' with variable foo=42
      add_host:
        name: "{{ ec2.instances[0].public_dns_name }}"
        groups: ec2_hosts
        ansible_host: "{{ ec2.instances[0].public_dns_name }}"
        ansible_ssh_user: ec2-user
        ansible_ssh_private_key_file: ~/mykey.pem
  
    - name: Wait for a while
      pause: seconds=30

- name: Install Apache on ec2 
  hosts: ec2_hosts
  become: yes 
  tasks:
    - yum: name=httpd state=installed
    - shell: systemctl start httpd.service
    - shell: systemctl enable httpd.service

- name: Install Mariadb on ec2 
  hosts: ec2_hosts
  become: yes 
  tasks:    
    - yum: name=mariadb-server state=installed
    - yum: name=mariadb state=installed
    - shell: systemctl start mariadb
    - command: mysql -u root -p 'Password123' -e "UPDATE mysql.user SET Password=PASSWORD('$password') WHERE User='root'; "
    - command: mysql -u root -p 'Password123' -e "DELETE FROM mysql.user WHERE User='root' AND Host not in ('localhost', '127.0.0.1' , '::1');"
    - command: mysql -u root -p 'Password123' -e "DELETE FROM mysql.user WHERE User='root' AND Host not in ('localhost', '127.0.0.1' , '::1');"
    - command: mysql -u root -p 'Password123' -e "DELETE FROM mysql.user WHERE User='';"
    - command: mysql -u root -p 'Password123' -e "DROP DATABASE test;"
    - command: mysql -u root -p 'Password123' -e "FLUSH PRIVILEGES;"
    - shell:  systemctl enable mariadb

- name: Install PHP on ec2
  hosts: ec2_hosts
  become: yes
  tasks: 
    - yum: name=php state=installed
    - yum: name=libapache2-mod-php state=installed
    - yum: name=php-mysql state=installed
    - shell: systemctl restart httpd.service

- name: Create user for Mysql
  hosts: ec2_hosts
  become: yes
  tasks:
    - command: mysql -u root -p$password -e "CREATE DATABASE IF NOT EXISTS wordpress;"
    - command: mysql -u root -p$password -e "CREATE USER IF NOT EXISTS wpuser@localhost IDENTIFIED BY 'user1pwd';"
    - command: mysql -u root -p$password -e "GRANT ALL PRIVILEGES ON wordpress.* TO wpuser@localhost IDENTIFIED BY 'user1pwd';"
    - command: mysql -u root -p$password -e "FLUSH PRIVILEGES;"

- name: Install wordpress
  hosts: ec2_hosts
  become: yes
  tasks:
    - yum: name=php-gd state=installed
    - wget: https://wordpress.org/wordpress-5.1.1.tar.gz state=installed
    - shell: tar -xzf wordpress-5.1.1.tar.gz
    - shell: rsync -avP ~/wordpress/ /var/www/html/
    - shell: mkdir /var/www/html/wp-content/uploads
    - shell: chown -R apache:apache /var/www/html/*
    - shell: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
    - shell: sed -i s/database_name_here/wordpress/ /var/www/html/wp-config.php
    - shell: sed -i s/username_here/wordpressuser/ /var/www/html/wp-config.php
    - shell: sed -i s/password_here/password/ /var/www/html/wp-config.php
    - shell: echo "#########################################################"
    - shell: echo "#########   Wordpress installed successfully  .##########" 
    - shell: echo "#########################################################"
    